[".config/nvim"]
    type = "archive"
    url = "https://github.com/ptrant/nvim-config/archive/main.zip"
    exact = false  # keep downloaded plugins
    stripComponents = 1
    refreshPeriod = "168h"

